### PR TITLE
Bump some Golang dependencies

### PR DESCRIPTION
**Pull request by juadk**
Fix this issue https://github.com/rancher/elemental/runs/8124047778?check_suite_focus=true

### CODE REVIEW

**Review by Itxaka — APPROVED** [review]

**Comment by ldevulder** [comment]
To avoid doing this each time a module version is bumped, maybe we can do this:
- remove `go.sum` file
- have `go.mod` with only this:
```
module github.com/rancher/elemental/tests

go 1.18
```
- do these command in the `make deps` section:
```
deps: 
        go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
        go install -mod=mod github.com/onsi/gomega
        go mod tidy
```

In that cse the latest versions of `ginkgo` and `gomega` are downloaded and all the deps are calculated with the 'mod tidy` command on each run. This will avoid CI issues on the tests. Tested locally ob my lab and it seems to works.

@juadk @Itxaka WDYT?

**Comment by Itxaka** [comment]
I no longer understand go dependencies and I dont want to. If that works @ldevulder then its good to me.

**Comment by juadk** [comment]
@ldevulder Let's go with your solution!

**Comment by ldevulder** [comment]
I just pushed the changes :-)

**Review by Itxaka — APPROVED** [review]

**Pull request merged**
