### PR TITLE
Include OBS workflow for Dev and Staging packages update in OBS

### PR DESCRIPTION
**Pull request by davidcassany**
Signed-off-by: David Cassany <dcassany@suse.com>

### CODE REVIEW

**Review by Itxaka — APPROVED** [review]
Nice

**Comment by Itxaka** [comment]
I guess the movement from staging to release will be a manual thing

**Comment by davidcassany** [comment]
> I guess the movement from staging to release will be a manual thing

Yes this is the idea, note that `Staging` and `Stable` subprojects do not exist yet. Stable should be set manually by pointing the `_service` file to specific tag from sources.

**Comment by davidcassany** [comment]
It worked `isv:Rancher:Elemental:Dev/elemental` got updated on merging 😉

**Pull request merged**
