### PR TITLE
Enable quotes on /etc/os-release

### PR DESCRIPTION
**Pull request by Itxaka**
Otherwise we get failures when we source the file

Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Comment by Itxaka** [comment]
nope, not right yet :/

**Comment by Itxaka** [comment]
Now its fixed!

**Comment by kkaempf** [comment]
Hmm, you're **re**-creating `/etc/os-release` here and thereby overwriting a file owned by the OS.
This is not acceptable for re-distributable images.

**Comment by Itxaka** [comment]
> Hmm, you're re-creating /etc/os-release here and thereby overwriting a file owned by the OS.
This is not acceptable for re-distributable images.

Has been like this since the start, Im just fixing an issue with quotes not being in there `¯\_(ツ)_/¯`

**Comment by kkaempf** [comment]
What's the purpose of `Dockerfile.image` ?
Even if it's just used for CI testing, it might give false test results. /etc/os-release _is_ used by (resp. a plan executed by) e.g. `rancher-system-agent`

**Comment by Itxaka** [comment]
> What's the purpose of Dockerfile.image ?

To build an elemental OCI image? One that can be used by the Makefile.iso to build a final iso? One that can be tested by anyone easily?

> Even if it's just used for CI testing, it might give false test results. /etc/os-release is used by (resp. a plan executed by) e.g. rancher-system-agent

I know, that is why those values are in there, to be used by the system-agent? We do the same on OBS, we override those values on os-release so they can be picked by the populate-node-labels for example?

Im not sure what is your objection to this? This produces a working image and ISO from the source code in this repo. One that can be tested before changes are merged. Should we just drop this? Im not sure how are we expected to not only CI test elemental but develop it? I am using this dockerfiles to test changes to everything, from the final elemental image, to the iso generation, to the cloud-configs and even new versions of the operator, as its easily overridable.

Can you state clearly your objection to this change, which actually fixes an issue in existing code (since the beginning of elemental even)?

**Comment by Itxaka** [comment]
BTW, this does not affect anything on OBS or the official images.

**Review by fgiudici — APPROVED** [review]
This change just adds quotes to the values in /etc/os-release, fixing /etc/os-release (quotes are expected there).
So, also if we will decide soon to remove the whole os-release rewrite section in the Dockerfile, applying this change will just fix the format (no change to the vaules) of os-release file. So, I would merge this.
LGTM

**Comment by kkaempf** [comment]
> BTW, this does not affect anything on OBS or the official images.

:eyes:

**Comment by kkaempf** [comment]
> 
> Can you state clearly your objection to this change, which actually fixes an issue in existing code (since the beginning of elemental even)?

/etc/os-release is part of the operating system, used as an identifier on many occasions.

While we can _add_ to it (like adding a TIMESTAMP by the node-image Dockerfile in OBS), we must not rewrite it.

**Comment by Itxaka** [comment]
wait, so its ok if I append a `NAME=whatever` to the file at the end, which will overwrite the original value as it will be loaded later in the file when doing a source `/etc/os-release` ??

I know its an identifier, and we override that as we are constructing a derived work from the original. But Im not sure what does that has anything to do with this PR, and why we must do that, is that on the license agreement of using the dockerfile? 

Would also be ok to NOT copy the file from the original source and just create one ourselves? In that case we would not be modifying anything, but creating the file from scratch?

I just dont see the reasoning, nor what it has to do with this PR, nor why it even matters lol So many workarounds around that that I cant even see how is that an issue.

**Comment by Itxaka** [comment]
@kkaempf removed all uneeded keys and avoided overwriting the file. Now we only add our extra values in there.

**Review by kkaempf — APPROVED** [review]
Thank you !

**Pull request merged**
