### PR TITLE
Bootstrap a node to join UI (Cypress)

### LINKED ISSUE #295: UI - Test Machine Inventory with Cypress

### PR DESCRIPTION
**Pull request by juadk**
Fix #295 

As Machine Registration tests are done, now we need to deploy a node and check that it appears in the Elemental UI in Machine Inventory.

Verification run:
https://github.com/rancher/elemental/actions/runs/3014527774

### CODE REVIEW

**Comment by juadk** [comment]
ok, good progress, I can deploy a new VM and it appears in the UI:
image
Let's continue with Cypress.

**Comment by juadk** [comment]
image

**Comment by juadk** [comment]
The code is ready but the GHA is stuck whereas the cluster is active in the UI...
image
image
I'm trying to debug...

**Comment by juadk** [comment]
Trying to run the test with cluster creation step commented out...

**Comment by juadk** [comment]
After a lot of debugging, this line is the culprit but TBH, I don't know why...
`cy.contains('Cluster: myelementalcluster Active', {timeout: 240000});`
I'm trying to find out another way to check that the cluster is ok.

**Comment by juadk** [comment]
Final word... test is green. It looks to be an issue with Chrome because all good with Firefox.

**Review by ldevulder — APPROVED** [review]
LGTM!

Let's see if we can avoid code duplication in `ui_test.go` later ;-)

**Pull request merged**
