### PR TITLE
Drop docs/ and examples/ directories

### PR DESCRIPTION
**Pull request by kkaempf**
Everything is in https://github.com/rancher/elemental-docs/ now

Signed-off-by: Klaus Kämpf <kkaempf@suse.de>

### CODE REVIEW

**Review by Itxaka — APPROVED** [review]

**Comment by kkaempf** [comment]
See also rancher/elemental-docs#28

**Review by mjura — COMMENTED** [review]
It seems that CI needs to be adjusted also 

```
Error:  Unable to build website for locale en.
21
Error:  Error: The docs folder does not exist for version "current". A docs folder is expected to be found at docs.
```

**Review by juadk — COMMENTED** [review]
I was doing the same for configuration files, could you also remove these files please? (I just  synced with Nuno about that):
```
.github/workflows/docs.yaml
Vars.js
babel.config.js
docusaurus.config.js
sidebars.js
yarn.lock
src
static
```

I will take care about removing the unused dependencies in the `package.json` in a separate PR.

**Comment by kkaempf** [comment]
> I was doing the same for configuration files, could you also remove these files please? (I just synced with Nuno about that):
> 
> ```
> .github/workflows/docs.yaml
> Vars.js
> babel.config.js
> docusaurus.config.js
> sidebars.js
> yarn.lock
> src
> static
> ```

Done.

> 
> I will take care about removing the unused dependencies in the `package.json` in a separate PR.

Thanks !

**Review by Itxaka — APPROVED** [review]
11000 lines removed? yes please.

**Comment by ldevulder** [comment]
> I will take care about removing the unused dependencies in the `package.json` in a separate PR.

Done in PR #591.

**Pull request merged**
