### PR TITLE
Drop ros image build

### PR DESCRIPTION
**Pull request by kkaempf**
Drop obsolete `ros-image-build`

### CODE REVIEW

**Comment by Itxaka** [comment]
This will break all tests. https://github.com/rancher/elemental/issues/169

**Comment by ldevulder** [comment]
> Drop obsolete `ros-image-build`

But nothing to replace it?

**Comment by Itxaka** [comment]
> We have elemental-iso-build now

Nope, that doesn't work. They are completely different and it affects the whole CI pipeline. You can try substituting it in this PR and you will see :D

 - elemental-iso-build builds the iso FROM released obs images. It makes no sense to use that in the CI pipeline to test the current code as that completely ignores it.
 - elemental-iso-build doesnt bundle ros-installer anymore. e2e tests require that
 - moving from ros-installer to elemental-operator register means that we need a rancher server spin up for e2e tests...kind of a big thing
 - if instead moving from ros-installer to elemental install, we still need stuff to adapt AND that will not properly test the use case that we want (boot a machine with elemental and a registration-url, see that it ends up working)

**Comment by ldevulder** [comment]
> * moving from ros-installer to elemental-operator register means that we need a rancher server spin up for e2e tests...kind of a big thing

It's already done :-) the E2E tests install k3s+rancher and then create 4 VMs for test OS bootstrapping, cluster creation and upgrade.

**Comment by ldevulder** [comment]
These changes have been done (with build refactoring!) in Itxaka PR #178, so this PR could be closed.

**Pull request closed without merging**
