### PR TITLE
Use elemental's build-iso command to build the ISO

### PR DESCRIPTION
**Pull request by davidcassany**
Signed-off-by: David Cassany <dcassany@suse.com>

### CODE REVIEW

**Review by Itxaka — APPROVED** [review]

**Comment by mudler** [comment]
Do we still need to build a config file?

**Comment by davidcassany** [comment]
> Do we still need to build a config file?

You mean the manifest embedded inside the Dockerfile? if so yes, there are no defaults set for the included packages as there is no Luet default configuration too. Note that those packages relay on  a Luet repository, so I am not sure having a default for everything is that good (I mean packages list and luet repositories). Anyway this is something simple to add if we want, it is all configurable via manifest and flags, so adding some extra defaults is trivial.

**Comment by mudler** [comment]
> > Do we still need to build a config file?
> 
> You mean the manifest embedded inside the Dockerfile? if so yes, there are no defaults set for the included packages as there is no Luet default configuration too. Note that those packages relay on a Luet repository, so I am not sure having a default for everything is that good (I mean packages list and luet repositories). Anyway this is something simple to add if we want, it is all configurable via manifest and flags, so adding some extra defaults is trivial.

I thought was already like this so we could get rid of the base file as there are no big customization here (just the iso overlay, which I thought you could pass with some arg), at the end a full manifest could be still passed by in case of overrides. Nevertheless looks good anyway, it's a nice cutdown!

**Review by mudler — APPROVED** [review]

**Comment by davidcassany** [comment]
> I thought was already like this so we could get rid of the base file as there are no big customization here (just the iso overlay, which I thought you could pass with some arg), at the end a full manifest could be still passed by in case of overrides. Nevertheless looks good anyway, it's a nice cutdown!

I did not add these defaults for everything as I had in mind the idea of having it always executed on top of a generic manifest and apply all little customizations on top of it. I also thought about having a default `--config-dir` value set to `.` or something like so we load the manifest from the current folder (even this does not really apply on this `os2` setup, but nice from a cOS-Toolkit PoV). Anyway the main reason to not add thiese defaults is having to hardcode the luet repository URL. To me it feels odd hardcoding it inside elemental, but we can easily do a follow up PR for that and discuss it, I do not have any technical reason against it.

**Pull request merged**
