### PR TITLE
docs: add architecture overview diagram

### PR DESCRIPTION
**Pull request by fgiudici**
Tried to draw an overview of the Elemental architecture.
While it is incomplete and not that great it may be of some use in following the architecture description.

Made with [excalidraw](https://excalidraw.com/), added the source file for easier modifications.

### CODE REVIEW

**Comment by Itxaka** [comment]
awesome, love the fonts, seems much nicer than the usual diagrams!

The only issue I can see is that there are no numbers, so its a bit confusing what comes first and second, i.e. the workflow, which is what thisis trying to represent no? Are we gonna add numbers and then explain in the docs the workflow associated with those number or is this a big picture diagram in which we only show the pieces and interaction and dont go deeper?

**Review by alexander-demicev — APPROVED** [review]
very nice!

**Review by davidcassany — APPROVED** [review]
:+1:

**Comment by fgiudici** [comment]
On hold: let's first migrate to docusaurus, then will rework the PR on that.

**Review by mjura — APPROVED** [review]
LGTM

**Comment by fgiudici** [comment]
docs have been migrated to [rancher/elemental-docs](https://github.com/rancher/elemental-docs).
The text changed in this PR has been already added in current docs.
The architecture diagram will be worked on in https://github.com/rancher/elemental-docs/pull/37.

**Pull request closed without merging**
