### PR TITLE
Add elemental-support binary in generated image

### PR DESCRIPTION
**Pull request by ldevulder**
This could be useful for debugging purposes

### CODE REVIEW

**Comment by kkaempf** [comment]
I'd like to see a submit request in OBS 😉

**Comment by ldevulder** [comment]
> I'd like to see a submit request in OBS

The main "issue" is that it's already done in images generated in OBS, but I don't know how... I will check to find what does this.

**Comment by ldevulder** [comment]
> The main "issue" is that it's already done in images generated in OBS, but I don't know how... I will check to find what does this.

Found: https://build.opensuse.org/package/view_file/isv:Rancher:Elemental/elemental-operator/elemental-operator.spec?expand=1

It's included in the package and so installed by it.

@kkaempf so I think there's nothing to do on OBS, no?

**Comment by kkaempf** [comment]
🤦🏻 - I totally forgot. Let me make this a sub-package. Consider it fixed in OBS.

**Pull request merged**
