### PR TITLE
Update bootargs.cfg

### PR DESCRIPTION
**Pull request by Itxaka**
Test disabling rd.neednet

### CODE REVIEW

**Review by kkaempf — APPROVED** [review]
fixes #25 🤞🏻

**Comment by kkaempf** [comment]
How does this relate to https://github.com/rancher/elemental/blob/0a9679fe457322baf3426549ad99811832d9b2eb/tests/smoke/smoke_test.go#L93 ?

Also there's `framework/files/etc/cos/bootargs.cfg` and `framework/cos/etc/cos/bootargs.cfg` and the OBS package build overwrites the latter with the former 🤦🏻

**Comment by Itxaka** [comment]
Ignore the tests, they currently don't run and @ldevulder is working on restoring them.

**Comment by Itxaka** [comment]
Framework/cos is the default files needed from elemental-toolkit and then we override them with the especific elemental ones.

It's on the readme, as it explains that those cos files get auto updated from elemental-toolkit, while the files ones are overlayed on top. Things like the default services from cos (cos-setup-fs for example) are part of the cos framework, while other services like the elemental-system-agent are elemental specific and go into the files folder.

Could probably do with a cleanup and merge of those, not sure what we would lose by just merging them....

**Comment by ldevulder** [comment]
> Ignore the tests, they currently don't run and @ldevulder is working on restoring them.

I'm on the E2E tests, not this smoke on yet, but I can re-add them later for sure. Is these smoke tests were part ofwhat was called Integration Tests?

**Comment by Itxaka** [comment]
> I'm on the E2E tests, not this smoke on yet, but I can re-add them later for sure. Is these smoke tests were part ofwhat was called Integration Tests?

yep, it run the tests under the smoke dir only :)

**Pull request merged**
