### PR TITLE
Install kernel-firmware-all package

### PR DESCRIPTION
**Pull request by kkaempf**
Signed-off-by: Klaus Kämpf <kkaempf@suse.de>

### CODE REVIEW

**Comment by Itxaka** [comment]
This affects the image size by a lot, doesn't it? Maybe we should have a slim and full images? Otherwise we are talking about applying updates that are what, 900mb? A bit big

**Review by Itxaka — APPROVED** [review]

**Comment by kkaempf** [comment]
> This affects the image size by a lot, doesn't it? Maybe we should have a slim and full images? Otherwise we are talking about applying updates that are what, 900mb? A bit big

Agreed - but what is 'slim' and what is 'big' ? There's always something missing and something superfluous 🤷🏻 
/cc @agracey

**Comment by agracey** [comment]
> but what is 'slim' and what is 'big'

My naive suggestion would be:
- Slim is the most minimal that can boot on common hardware (VMs, NUCs, raspberry pis, etc)
- Full is everything (opensource) you would expect to need in 90% of environments 


Then, most people would start with full to learn how the tooling works then move to the slim and add additional packages.

**Comment by kkaempf** [comment]
> Then, most people would start with full to learn how the tooling works then move to the slim and add additional packages.

I fear we need a way to support such setups 🙈

**Comment by kkaempf** [comment]
> Would it make sense to schedule a sprint after the next release looking at image size and varietals?

You can see image sizes [here](https://download.opensuse.org/repositories/isv:/Rancher:/Elemental:/Dev:/Teal53/media/iso/) (iso) and [here](https://download.opensuse.org/repositories/isv:/Rancher:/Elemental:/Dev:/Teal53/images/) (Raspberry image).

If image sizes are a concern, we can add a card to look at minimizing the image (by removing unneeded stuff pulled in by rpm deps)

**Pull request merged**
