### PR TITLE
Drop ros-operator-install and rename populate-node-labels script

### PR DESCRIPTION
**Pull request by mudler**
Fixes: https://github.com/rancher/elemental/issues/166

Signed-off-by: Ettore Di Giacinto <edigiacinto@suse.com>

### CODE REVIEW

**Review by kkaempf — APPROVED** [review]
lgtm

**Comment by kkaempf** [comment]
> mmh. ros-operator-install seems to be used here:
> 
> https://github.com/rancher/elemental/blob/c3e62ce672b1f3cf3babd41df9cac9426df84326/framework/files/usr/share/rancher/rancherd/config.yaml#L2
> 
> but as rancherd is no more.. I guess we shouldn't care?

Right.
That's probably worth an issue in rancher/elemental.

**Comment by Itxaka** [comment]
Ros-operator-install was dropped as part of #178

**Comment by Itxaka** [comment]
I think this is still being called somewhere in the systemd services and the systemd services are also names wrongly 🙂

**Pull request merged**
