### PR TITLE
Fixed typos in quickstart.md

### PR DESCRIPTION
**Pull request by simonflood**
Signed-off-by: Simon Flood <simonflood@users.noreply.github.com>

### CODE REVIEW

**Review by Itxaka — APPROVED** [review]
Thanks!

**Comment by Itxaka** [comment]
cc @nunix we will need to move this into the https://github.com/rancher/elemental-docs repo :=)

**Comment by simonflood** [comment]
Might be worth removing rancher/elemental/docs in favour of rancher/elemental-docs or at least noting in rancher/elemental/docs/readme.md that docs have moved. At least I now know where to make corrections! :wink:

**Comment by Itxaka** [comment]
> Might be worth removing rancher/elemental/docs in favour of rancher/elemental-docs or at least noting in rancher/elemental/docs/readme.md that docs have moved. At least I now know where to make corrections! :wink: 

Indeed, I think the plan is to start publishing from the new repo this week, so by that point we can deprecate the docs in teh repo. I think you just got us in the middle of the transition 😉

**Pull request merged**
